// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SummitCms.Modules.SiteContent.Infrastructure;

#nullable disable

namespace SummitCms.Modules.SiteContent.Infrastructure.Migrations
{
    [DbContext(typeof(SiteContentDbContext))]
    partial class SiteContentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("content")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SummitCms.Modules.SiteContent.Domain.EnquiryType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_enquiry_types");

                    b.ToTable("enquiry_types", "content");
                });

            modelBuilder.Entity("SummitCms.Modules.SiteContent.Domain.MetricStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("GroupKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("group_key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uuid")
                        .HasColumnName("page_id");

                    b.Property<string>("Prefix")
                        .HasColumnType("text")
                        .HasColumnName("prefix");

                    b.Property<string>("Suffix")
                        .HasColumnType("text")
                        .HasColumnName("suffix");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_metric_stats");

                    b.HasIndex("PageId", "GroupKey")
                        .HasDatabaseName("ix_metric_stats_page_id_group_key");

                    b.ToTable("metric_stats", "content");
                });

            modelBuilder.Entity("SummitCms.Modules.SiteContent.Domain.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HeroHeading")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hero_heading");

                    b.Property<Guid?>("HeroMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("hero_media_id");

                    b.Property<string>("HeroSubheading")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hero_subheading");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meta_description");

                    b.Property<Guid?>("SecondaryMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("secondary_media_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_pages");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_pages_slug");

                    b.ToTable("pages", "content");
                });

            modelBuilder.Entity("SummitCms.Modules.SiteContent.Domain.SiteSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value_type");

                    b.HasKey("Id")
                        .HasName("pk_site_settings");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_site_settings_key");

                    b.ToTable("site_settings", "content");
                });

            modelBuilder.Entity("SummitCms.Modules.SiteContent.Domain.MetricStat", b =>
                {
                    b.HasOne("SummitCms.Modules.SiteContent.Domain.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_metric_stats_pages_page_id");

                    b.Navigation("Page");
                });
#pragma warning restore 612, 618
        }
    }
}
