// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SummitCms.Modules.Projects.Infrastructure;

#nullable disable

namespace SummitCms.Modules.Projects.Infrastructure.Migrations
{
    [DbContext(typeof(ProjectsDbContext))]
    partial class ProjectsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("projects")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SummitCms.Modules.Projects.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<Guid?>("HeroMediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("hero_media_id");

                    b.Property<Guid>("IndustryCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("industry_category_id");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_featured");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<string>("Ratio")
                        .HasColumnType("text")
                        .HasColumnName("ratio");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("slug");

                    b.Property<int?>("Span")
                        .HasColumnType("integer")
                        .HasColumnName("span");

                    b.Property<string>("Stat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stat");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("IndustryCategoryId")
                        .HasDatabaseName("ix_projects_industry_category_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_slug");

                    b.ToTable("projects", "projects");
                });

            modelBuilder.Entity("SummitCms.Modules.Projects.Domain.ProjectGalleryImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("caption");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_gallery_images");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_gallery_images_project_id");

                    b.ToTable("gallery_images", "projects");
                });

            modelBuilder.Entity("SummitCms.Modules.Projects.Domain.ProjectIndustryCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_industry_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_industry_categories_name");

                    b.ToTable("industry_categories", "projects");
                });

            modelBuilder.Entity("SummitCms.Modules.Projects.Domain.ProjectNarrativeParagraph", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("NarrativeSectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("narrative_section_id");

                    b.Property<int>("ParagraphOrder")
                        .HasColumnType("integer")
                        .HasColumnName("paragraph_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_narrative_paragraphs");

                    b.HasIndex("NarrativeSectionId")
                        .HasDatabaseName("ix_narrative_paragraphs_narrative_section_id");

                    b.ToTable("narrative_paragraphs", "projects");
                });

            modelBuilder.Entity("SummitCms.Modules.Projects.Domain.ProjectNarrativeSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Idx")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idx");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_narrative_sections");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_narrative_sections_project_id");

                    b.ToTable("narrative_sections", "projects");
                });

            modelBuilder.Entity("SummitCms.Modules.Projects.Domain.ProjectQuote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Attribution")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attribution");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quote");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_quotes");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_quotes_project_id");

                    b.ToTable("quotes", "projects");
                });

            modelBuilder.Entity("SummitCms.Modules.Projects.Domain.ProjectScopeFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_scope_facts");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_scope_facts_project_id");

                    b.ToTable("scope_facts", "projects");
                });

            modelBuilder.Entity("SummitCms.Modules.Projects.Domain.Project", b =>
                {
                    b.HasOne("SummitCms.Modules.Projects.Domain.ProjectIndustryCategory", "IndustryCategory")
                        .WithMany()
                        .HasForeignKey("IndustryCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_industry_categories_industry_category_id");

                    b.Navigation("IndustryCategory");
                });

            modelBuilder.Entity("SummitCms.Modules.Projects.Domain.ProjectGalleryImage", b =>
                {
                    b.HasOne("SummitCms.Modules.Projects.Domain.Project", "Project")
                        .WithMany("GalleryImages")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gallery_images_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SummitCms.Modules.Projects.Domain.ProjectNarrativeParagraph", b =>
                {
                    b.HasOne("SummitCms.Modules.Projects.Domain.ProjectNarrativeSection", "NarrativeSection")
                        .WithMany("Paragraphs")
                        .HasForeignKey("NarrativeSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_narrative_paragraphs_narrative_sections_narrative_section_id");

                    b.Navigation("NarrativeSection");
                });

            modelBuilder.Entity("SummitCms.Modules.Projects.Domain.ProjectNarrativeSection", b =>
                {
                    b.HasOne("SummitCms.Modules.Projects.Domain.Project", "Project")
                        .WithMany("NarrativeSections")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_narrative_sections_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SummitCms.Modules.Projects.Domain.ProjectQuote", b =>
                {
                    b.HasOne("SummitCms.Modules.Projects.Domain.Project", "Project")
                        .WithOne("Quote")
                        .HasForeignKey("SummitCms.Modules.Projects.Domain.ProjectQuote", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quotes_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SummitCms.Modules.Projects.Domain.ProjectScopeFact", b =>
                {
                    b.HasOne("SummitCms.Modules.Projects.Domain.Project", "Project")
                        .WithMany("ScopeFacts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scope_facts_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SummitCms.Modules.Projects.Domain.Project", b =>
                {
                    b.Navigation("GalleryImages");

                    b.Navigation("NarrativeSections");

                    b.Navigation("Quote");

                    b.Navigation("ScopeFacts");
                });

            modelBuilder.Entity("SummitCms.Modules.Projects.Domain.ProjectNarrativeSection", b =>
                {
                    b.Navigation("Paragraphs");
                });
#pragma warning restore 612, 618
        }
    }
}
